In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [11]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[1] + arr[5]

8

In [16]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:

matriz[0,2]

3

In [22]:
matriz[0][2]


3

In [23]:
arr[0:3]

array([1, 2, 3])

In [24]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [25]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[::3]

array([1, 4, 7])

In [28]:
arr[-1]

9

ultimos tres

In [29]:
arr[-3:]

array([7, 8, 9])

In [30]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])