In [2]:
import numpy as np
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
indice = arr > 5

In [7]:
arr[indice]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [12]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [14]:
arr[arr > 5 ] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [15]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)