In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr2 = arr[0:6]

In [6]:
arr2[:] = 0

In [7]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [11]:
arr2 = arr.copy()
arr2 = arr2[:6]
arr2[:] = 100 

In [12]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [13]:
arr2

array([100, 100, 100, 100, 100, 100])