In [15]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [17]:
arr = np.array([1, 2, 3, 4, 5], dtype='float64')
arr.dtype


dtype('float64')

In [18]:
arr

array([1., 2., 3., 4., 5.])

In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype


dtype('int64')

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [22]:
arr = np.array([0,1, 2, 3, 4, 5])
arr = arr.astype(np.bool_)
arr


array([False,  True,  True,  True,  True,  True])

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.string_)
arr


array([b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

In [25]:
arr = np.array(['1', '2', '3', '4', '5'])
arr = arr.astype(np.int8)
arr


array([1, 2, 3, 4, 5], dtype=int8)