In [7]:
import numpy as np

In [8]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [9]:
vector = np.array([4,5,6])
print(vector)
vector.ndim


[4 5 6]


1

In [10]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [11]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(tensor)
tensor.ndim


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [12]:
#agregar o eliminar 
tensor = np.array([4, 5, 6],ndmin=10)
print(tensor)
tensor.ndim


[[[[[[[[[[4 5 6]]]]]]]]]]


10

In [17]:
#axis = 0 nivel de filas
'''[[4 5 6]]'''
#axis = 1 nivel de columnas
'''
[[4]
 [5]
 [6]]
'''
expand = np.expand_dims(np.array([4, 5, 6]), axis=1)
print(expand)
expand.ndim

[[4]
 [5]
 [6]]


2

In [20]:
#eliminar dimensiones
print(tensor,tensor.ndim)
vector = np.squeeze(tensor)
print(vector,vector.ndim)


[[[[[[[[[[4 5 6]]]]]]]]]] 10
[4 5 6] 1
