In [34]:
import numpy as np

In [35]:
vector  = np.random.randint(1,20,10)
vector

array([19, 12, 17, 12, 19, 17,  8,  3, 17,  2])

In [36]:
matriz = vector.reshape(2,5)
matriz

array([[19, 12, 17, 12, 19],
       [17,  8,  3, 17,  2]])

In [37]:
vector.max()

19

In [38]:
matriz.max()

19

In [39]:
matriz.max(1)

array([19, 17])

In [40]:
matriz.max(0)


array([19, 12, 17, 17, 19])

In [41]:
vector.argmax()

0

In [42]:
matriz

array([[19, 12, 17, 12, 19],
       [17,  8,  3, 17,  2]])

In [43]:
matriz.argmax(0)

array([0, 0, 0, 1, 0])

In [44]:
vector.min()

2

In [45]:
matriz.min()

2

In [46]:
vector.argmin()

9

In [47]:
matriz.argmin(0)

array([1, 1, 1, 0, 1])

In [48]:
vector

array([19, 12, 17, 12, 19, 17,  8,  3, 17,  2])

In [49]:
vector.ptp()

17

In [50]:
matriz

array([[19, 12, 17, 12, 19],
       [17,  8,  3, 17,  2]])

In [51]:
matriz.ptp(0)

array([ 2,  4, 14,  5, 17])

In [52]:
matriz.ptp(1)

array([ 7, 15])

In [53]:
np.percentile(vector,50)

14.5

In [54]:
np.percentile(vector,0)

2.0

In [55]:
np.percentile(vector,100)

19.0

In [56]:
vector.sort()
vector

array([ 2,  3,  8, 12, 12, 17, 17, 17, 19, 19])

In [57]:
np.percentile(vector,50)

14.5

In [58]:
np.median(vector)

14.5

In [59]:
np.median(matriz,1)

array([ 8., 17.])

In [60]:
#desviacion estandar
np.std(vector)

6.053098380168622

In [61]:
#varianza
np.var(vector)

36.64

In [62]:
#media
np.mean(vector)

12.6

In [63]:
a = np.array([[1,2],[3,4]])
a.ndim

2

In [64]:
b = np.array([5,6])
b.ndim


1

In [66]:
b = np.expand_dims(b,axis=0)
b.ndim

2

In [67]:

np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
#transpuesta de una matriz

np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])