In [73]:
import numpy as np 
lista = [1,2]
lista

[1, 2]

In [74]:
lista * 2

[1, 2, 1, 2]

In [75]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
1 / arr

/tmp/ipykernel_328/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [80]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [81]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [82]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [85]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [87]:
#producto punto
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [88]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])