In [45]:
import numpy as np

In [46]:
arr = np.random.randint(1,10,(3,2))

arr

array([[1, 6],
       [2, 4],
       [8, 2]])

In [47]:
arr.shape

(3, 2)

In [48]:
arr.reshape(1,6)

array([[1, 6, 2, 4, 8, 2]])

In [49]:
arr.reshape(2,3)

array([[1, 6, 2],
       [4, 8, 2]])

In [50]:
np.reshape(arr,(1,6))

array([[1, 6, 2, 4, 8, 2]])

In [51]:
arr

array([[1, 6],
       [2, 4],
       [8, 2]])

In [52]:
np.reshape(arr,(2,3),'C')

array([[1, 6, 2],
       [4, 8, 2]])

In [54]:
arr

array([[1, 6],
       [2, 4],
       [8, 2]])

In [53]:
np.reshape(arr,(2,3),'F')

array([[1, 8, 4],
       [2, 6, 2]])

In [55]:
np.reshape(arr,(2,3),'A')

array([[1, 6, 2],
       [4, 8, 2]])